# Read the current file
with open('ReceptionistDashboard.jsx', 'r') as f:
    content = f.read()

# Find the exact line 554 and replace it with comprehensive room management section
lines = content.split('\n')

# Find line 554 (index 553, since arrays are 0-based)
for i, line in enumerate(lines):
    if i == 553 and line.strip() == ') : (':
        # Replace with comprehensive room management section
        lines[i] = ') : showRoomManagement ? ('
        lines.insert(i+1, '                <div className="bg-white rounded-lg shadow p-6">')
        lines.insert(i+2, '                  <div className="flex justify-between items-center mb-4">')
        lines.insert(i+3, '                    <h3 className="text-lg font-medium text-gray-900">Room Management (Branch-Based)</h3>')
        lines.insert(i+4, '                    <button')
        lines.insert(i+5, '                      onClick={() => setShowRoomManagement(false)}')
        lines.insert(i+6, '                      className="text-sm text-gray-500 hover:text-gray-700"')
        lines.insert(i+7, '                    >')
        lines.insert(i+8, '                      ← Back to Dashboard')
        lines.insert(i+9, '                    </button>')
        lines.insert(i+10, '                  </div>')
        lines.insert(i+11, '                  <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-6">')
        lines.insert(i+12, '                    {/* Room Categories per branch */}')
        lines.insert(i+13, '                    <div className="bg-gray-50 rounded-lg p-4">')
        lines.insert(i+14, '                      <h4 className="text-sm font-medium text-gray-700 mb-3">Room Categories</h4>')
        lines.insert(i+15, '                      <div className="grid grid-cols-2 md:grid-cols-3 gap-2">')
        lines.insert(i+16, '                        <div className="text-center p-3 bg-white rounded border">')
        lines.insert(i+17, '                          <div className="text-2xl font-bold text-blue-600">4</div>')
        lines.insert(i+18, '                          <div className="text-xs text-gray-500">Standard</div>')
        lines.insert(i+19, '                        </div>')
        lines.insert(i+20, '                        <div className="text-center p-3 bg-white rounded border">')
        lines.insert(i+21, '                          <div className="text-2xl font-bold text-green-600">2</div>')
        lines.insert(i+22, '                          <div className="text-xs text-gray-500">Deluxe</div>')
        lines.insert(i+23, '                        </div>')
        lines.insert(i+24, '                        <div className="text-center p-3 bg-white rounded border">')
        lines.insert(i+25, '                          <div className="text-2xl font-bold text-purple-600">3</div>')
        lines.insert(i+26, '                          <div className="text-xs text-gray-500">Suite</div>')
        lines.insert(i+27, '                        </div>')
        lines.insert(i+28, '                      </div>')
        lines.insert(i+29, '                    </div>')
        lines.insert(i+30, '                    {/* Room Inventory per branch */}')
        lines.insert(i+31, '                    <div className="bg-gray-50 rounded-lg p-4">')
        lines.insert(i+32, '                      <h4 className="text-sm font-medium text-gray-700 mb-3">Room Inventory</h4>')
        lines.insert(i+33, '                      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">')
        lines.insert(i+34, '                        {rooms.map((room) => (')
        lines.insert(i+35, '                          <div key={room._id} className="border border-gray-200 rounded-lg p-4 hover:shadow-md transition-shadow">')
        lines.insert(i+36, '                            <div className="flex justify-between items-start mb-3">')
        lines.insert(i+37, '                              <div>')
        lines.insert(i+38, '                                <h5 className="text-lg font-semibold text-gray-900">Room {room.roomNumber}</h5>')
        lines.insert(i+39, '                                <p className="text-sm text-gray-500">{room.category}</p>')
        lines.insert(i+40, '                              </div>')
        lines.insert(i+41, '                              <span className={`px-2 py-1 text-xs font-medium rounded-full ${')
        lines.insert(i+42, '                                room.status === "AVAILABLE" ? "bg-green-100 text-green-800" :')
        lines.insert(i+43, '                                room.status === "OCCUPIED" ? "bg-red-100 text-red-800" :')
        lines.insert(i+44, '                                room.status === "CLEANING" ? "bg-yellow-100 text-yellow-800" :')
        lines.insert(i+45, '                                "bg-gray-100 text-gray-800"')
        lines.insert(i+46, '                              }`}>')
        lines.insert(i+47, '                                {room.status}')
        lines.insert(i+48, '                              </span>')
        lines.insert(i+49, '                            </div>')
        lines.insert(i+50, '                            <div className="grid grid-cols-2 gap-2 text-sm text-gray-600">')
        lines.insert(i+51, '                              <div>Price: ${room.basePrice}/night</div>')
        lines.insert(i+52, '                              <div>Capacity: {room.capacity} guests</div>')
        lines.insert(i+53, '                              <div>Floor: {room.floor || "N/A"}</div>')
        lines.insert(i+54, '                            </div>')
        lines.insert(i+55, '                            {room.amenities && room.amenities.length > 0 && (')
        lines.insert(i+56, '                              <div className="mt-3">')
        lines.insert(i+57, '                                <p className="text-xs text-gray-500 mb-2">Amenities:</p>')
        lines.insert(i+58, '                                <div className="flex flex-wrap gap-1">')
        lines.insert(i+59, '                                  {room.amenities.map((amenity, index) => (')
        lines.insert(i+60, '                                    <span key={index} className="px-2 py-1 bg-gray-100 text-gray-700 text-xs rounded">{amenity}</span>')
        lines.insert(i+61, '                                  ))}')
        lines.insert(i+62, '                                </div>')
        lines.insert(i+63, '                              </div>')
        lines.insert(i+64, '                            ))}')
        lines.insert(i+65, '                          </div>')
        lines.insert(i+66, '                        ))}')
        lines.insert(i+67, '                      </div>')
        lines.insert(i+68, '                    {/* Pricing setup per branch */}')
        lines.insert(i+69, '                    <div className="bg-gray-50 rounded-lg p-4">')
        lines.insert(i+70, '                      <h4 className="text-sm font-medium text-gray-700 mb-3">Pricing Setup</h4>')
        lines.insert(i+71, '                      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">')
        lines.insert(i+72, '                        <div>')
        lines.insert(i+73, '                          <label className="block text-sm font-medium text-gray-700 mb-2">Base Price Multiplier</label>')
        lines.insert(i+74, '                          <input type="number" className="w-full px-3 py-2 border border-gray-300 rounded-md" placeholder="1.0" />')
        lines.insert(i+75, '                        </div>')
        lines.insert(i+76, '                        <div>')
        lines.insert(i+77, '                          <label className="block text-sm font-medium text-gray-700 mb-2">Weekend Surcharge (%)</label>')
        lines.insert(i+78, '                          <input type="number" className="w-full px-3 py-2 border border-gray-300 rounded-md" placeholder="20" />')
        lines.insert(i+79, '                        </div>')
        lines.insert(i+80, '                        <div>')
        lines.insert(i+81, '                          <label className="block text-sm font-medium text-gray-700 mb-2">Seasonal Rates</label>')
        lines.insert(i+82, '                          <select className="w-full px-3 py-2 border border-gray-300 rounded-md">')
        lines.insert(i+83, '                            <option>Enable seasonal pricing</option>')
        lines.insert(i+84, '                            <option>Disable seasonal pricing</option>')
        lines.insert(i+85, '                          </select>')
        lines.insert(i+86, '                        </div>')
        lines.insert(i+87, '                      </div>')
        lines.insert(i+88, '                      <button className="w-full bg-blue-600 text-white py-2 px-4 rounded-md hover:bg-blue-700">')
        lines.insert(i+89, '                        Save Pricing Settings')
        lines.insert(i+90, '                      </button>')
        lines.insert(i+91, '                    </div>')
        lines.insert(i+92, '                    {/* Room status management */}')
        lines.insert(i+93, '                    <div className="bg-gray-50 rounded-lg p-4">')
        lines.insert(i+94, '                      <h4 className="text-sm font-medium text-gray-700 mb-3">Room Status Management</h4>')
        lines.insert(i+95, '                      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">')
        lines.insert(i+96, '                        <button className="p-4 bg-green-100 text-green-800 rounded-lg hover:bg-green-200">')
        lines.insert(i+97, '                          <div className="text-lg font-semibold mb-2">Available</div>')
        lines.insert(i+98, '                          <div className="text-sm text-gray-600">Mark rooms as available for booking</div>')
        lines.insert(i+99, '                        </button>')
        lines.insert(i+100, '                        <button className="p-4 bg-red-100 text-red-800 rounded-lg hover:bg-red-200">')
        lines.insert(i+101, '                          <div className="text-lg font-semibold mb-2">Occupied</div>')
        lines.insert(i+102, '                          <div className="text-sm text-gray-600">Mark rooms as occupied</div>')
        lines.insert(i+103, '                        </button>')
        lines.insert(i+104, '                        <button className="p-4 bg-yellow-100 text-yellow-800 rounded-lg hover:bg-yellow-200">')
        lines.insert(i+105, '                          <div className="text-lg font-semibold mb-2">Cleaning</div>')
        lines.insert(i+106, '                          <div className="text-sm text-gray-600">Mark rooms as under cleaning/maintenance</div>')
        lines.insert(i+107, '                        </button>')
        lines.insert(i+108, '                      </div>')
        lines.insert(i+109, '                    </div>')
        lines.insert(i+110, '                  </div>')
        lines.insert(i+111, '                </div>')
        lines.insert(i+112, '              ) : (')
        break

# Write the modified content back
with open('ReceptionistDashboard.jsx', 'w') as f:
    f.write('\n'.join(lines))

print("Comprehensive room management section added successfully!")
